# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8f85ae70b488ff65cf749bf2f22a269b"
application_url = "https://semi-violin-starting-opinions.trycloudflare.com"
embedded = true
name = "uzerly-app-v2"
handle = "uzerly-app-v2"

[build]
include_config_on_deploy = true
dev_store_url = "t5698.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_pixels,read_customer_events"

[auth]
redirect_urls = [
  "https://semi-violin-starting-opinions.trycloudflare.com/auth/callback",
  "https://semi-violin-starting-opinions.trycloudflare.com/auth/shopify/callback",
  "https://semi-violin-starting-opinions.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
