# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "98ed6e016cab84163ef46b87072b3f0f"
application_url = "https://moves-pioneer-licking-sega.trycloudflare.com"
embedded = true
name = "test-uzerly"
handle = "test-uzerly"

[build]
include_config_on_deploy = true
dev_store_url = "t5698.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://moves-pioneer-licking-sega.trycloudflare.com/auth/callback",
  "https://moves-pioneer-licking-sega.trycloudflare.com/auth/shopify/callback",
  "https://moves-pioneer-licking-sega.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
