# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f48bad1b6948bca8341d79115ff28000"
application_url = "https://pacific-slovenia-blair-chains.trycloudflare.com"
embedded = true
name = "uzerly-app"
handle = "training-app-32"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_pixels,read_customer_events"

[auth]
redirect_urls = [
  "https://pacific-slovenia-blair-chains.trycloudflare.com/auth/callback",
  "https://pacific-slovenia-blair-chains.trycloudflare.com/auth/shopify/callback",
  "https://pacific-slovenia-blair-chains.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "t5698.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
