name = "uzerly-web-pixel"
type = "web_pixel_extension"


runtime_context = "strict"

[settings]
type = "object"

[settings.fields.advertiser]
name = "Advertiser"
description = "advertiser ID"
type = "single_line_text_field"
validations =  [
  { name = "min", value = "1" }
]

[settings.fields.offer]
name = "Offer"
description = "offer ID"
type = "single_line_text_field"
validations =  [
  { name = "min", value = "1" }
]
